#!/bin/zsh

_ymt_checkip_usage() {
  cat <<EOF
checkip displays the current IP address of the PC.

Usage:
    checkip        show your IP Address

Options:
    --help, -h        print help
EOF
}

case ${1} in
  -h|--help)
    _ymt_checkip_usage
  ;;

  *)
    curl -sS --max-time 10 https://checkip.amazonaws.com/ || echo "Error: Failed to get IP" >&2
  ;;
esac
