#!/bin/zsh

_ymt_docker_login_usage() {
  cat <<EOF
docker-login is a shortcut 'docker login' to Docker Hub, AWS ECR, GitHub Container Registory.

Usage:
    docker-login         login to Docker Hub
    docker-login ecr     login to AWS ECR
    docker-login ghcr    login to GitHub Container Registory

Options:
    --help, -h           print help

Configurable Environment Variables:
    AWS ECR:
        AWS_REGION=ap-northeast-1
        AWS_ECR_REPOSITORY={aws_account_id}.dkr.ecr.{your-aws-region}.amazonaws.com
    GitHub Container Registory:
        CR_PAT=your-github-access-token
        # ref: https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        GITHUB_ACCOUNT=your-github-account

Dependencies:
    awscli
    docker
EOF
}

_ymt_docker_login_ecr() {
  if [ -z "$AWS_REGION" ]; then
    read AWS_REGION\?'Enter AWS Region: '
    local aws_region=$AWS_REGION
    unset AWS_REGION
  else
    local aws_region=$AWS_REGION
  fi

  if [ -z "$AWS_ECR_REPOSITORY" ]; then
    read AWS_ECR_REPOSITORY\?'Enter AWS ECR Reporitoy URL: '
    local aws_ecr_repository=$AWS_ECR_REPOSITORY
    unset AWS_ECR_REPOSITORY
  else
    local aws_ecr_repository=$AWS_ECR_REPOSITORY
  fi

  aws ecr get-login-password --region $aws_region | docker login --username AWS --password-stdin $aws_ecr_repository
}

_ymt_docker_login_ghcr() {
  if [ -z "$CR_PAT" ]; then
    read CR_PAT\?'Enter GitHub Access Token: '
    local github_access_token=$CR_PAT
    unset CR_PAT
  else
    local github_access_token=$CR_PAT
  fi

  if [ -z "$GITHUB_ACCOUNT" ]; then
    read GITHUB_ACCOUNT\?'Enter GitHub Account: '
    local github_account=$GITHUB_ACCOUNT
    unset GITHUB_ACCOUNT
  else
    local github_account=$GITHUB_ACCOUNT
  fi

  echo $github_access_token | docker login ghcr.io -u $github_account --password-stdin
}

case ${1} in
  -h|--help)
    _ymt_docker_login_usage
  ;;

  ecr)
    _ymt_docker_login_ecr
  ;;

  ghcr)
    _ymt_docker_login_ghcr
  ;;

  *)
    docker login
  ;;
esac
