#!/bin/zsh

_ymt_docker_login_usage() {
  cat <<EOF
docker-login is a shortcut 'docker login' to Docker Hub, AWS ECR, GitHub Container Registory.

Usage:
    docker-login         login to Docker Hub
    docker-login ecr     login to AWS ECR
    docker-login ghcr    login to GitHub Container Registory

Options:
    --help, -h           print help

Configurable Environment Variables:
    AWS ECR:
        AWS_REGION=ap-northeast-1
        AWS_ECR_REPOSITORY={aws_account_id}.dkr.ecr.{your-aws-region}.amazonaws.com
    GitHub Container Registory:
        CR_PAT=your-github-access-token
        # ref: https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        GITHUB_ACCOUNT=your-github-account

Dependencies:
    awscli
    docker
EOF
}

_ymt_docker_login_ecr() {
  local aws_region=$AWS_REGION
  local aws_ecr_repository=$AWS_ECR_REPOSITORY

  if [ -z "$AWS_REGION" ]; then
    read -r aws_region\?'Enter AWS Region: '
  fi

  if [ -z "$AWS_ECR_REPOSITORY" ]; then
    read -r aws_ecr_repository\?'Enter AWS ECR Repository URL: '
  fi

  if [[ -z "$aws_region" || -z "$aws_ecr_repository" ]]; then
    echo "Error: AWS region and ECR repository URL are required" >&2
    return 1
  fi
  aws ecr get-login-password --region "$aws_region" | docker login --username AWS --password-stdin "$aws_ecr_repository"
}

_ymt_docker_login_ghcr() {
  local github_access_token=$CR_PAT
  local github_account=$GITHUB_ACCOUNT

  if [ -z "$CR_PAT" ]; then
    read -r github_access_token\?'Enter GitHub Access Token: '
  fi

  if [ -z "$GITHUB_ACCOUNT" ]; then
    read -r github_account\?'Enter GitHub Account: '
  fi

  if [[ -z "$github_access_token" || -z "$github_account" ]]; then
    echo "Error: GitHub access token and account are required" >&2
    return 1
  fi
  printf '%s' "$github_access_token" | docker login ghcr.io -u "$github_account" --password-stdin
}

case ${1} in
  -h|--help)
    _ymt_docker_login_usage
  ;;

  ecr)
    _ymt_docker_login_ecr
  ;;

  ghcr)
    _ymt_docker_login_ghcr
  ;;

  *)
    docker login
  ;;
esac
