#!/bin/zsh

if [ -z "$AWS_REGION" ]; then
  echo "Please set \$AWS_REGION. ex: export AWS_REGION={your-aws-region}"
  return
fi

if [ -z "$AWS_ECR_REPOSITORY" ]; then
  echo "Please set the ECR repository URL in \$AWS_ECR_REPOSITORY. ex: export AWS_ECR_REPOSITORY={aws_account_id}.dkr.ecr.{your-aws-region}.amazonaws.com"
  return
fi

aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
