#!/bin/zsh

function _ymt_ecr_login_usage() {
  cat <<EOF
ecr_login is a shortcut for AWS ECR login.

Usage:
    ecr-login         login to AWS ECR

Options:
    --help, -h        print help

Configurable Environment Variables:
    AWS_REGION=ap-northeast-1
    AWS_ECR_REPOSITORY={aws_account_id}.dkr.ecr.{your-aws-region}.amazonaws.com
EOF
}

function _ymt_ecr_login() {
  if [ -z "$AWS_REGION" ]; then
    read AWS_REGION\?'Enter AWS Region: '
  fi

  if [ -z "$AWS_ECR_REPOSITORY" ]; then
    read AWS_ECR_REPOSITORY\?'Enter AWS ECR Reporitoy URL: '
  fi

  aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
}

case ${1} in
  -h|--help)
    _ymt_ecr_login_usage
  ;;

  *)
    _ymt_ecr_login
  ;;
esac
