#!/bin/zsh

function _ymt_git_root_usage() {
  cat <<EOF
git_root move current_directory to project root dir.

Usage:
    git_root     change directory to project root

Options:
    --help, -h   print help

Dependencies:
    git
EOF
}

function _ymt_git_root() {
  local root_dir=$(git rev-parse --show-toplevel 2>/dev/null)
  if [ -z $root_dir ]; then
    echo 'not under git control.'
  else
    cd $root_dir
  fi
}

case ${1} in
  -h|--help)
    _ymt_git_root_usage
  ;;

  *)
    _ymt_git_root
esac
