#!/bin/zsh

_ymt_git_root_usage() {
  cat <<EOF
git_root move current_directory to project root dir.

Usage:
    git_root         change directory to git project root
    git_root show    show git project root

Options:
    --help, -h      print help

Dependencies:
    git
EOF
}

_ymt_git_root_dir() {
  local root_dir=$(git rev-parse --show-toplevel 2>/dev/null)
  if [[ -z "$root_dir" ]]; then
    echo 'not under git control.' >&2
    return 1
  fi
  echo "$root_dir"
}

_ymt_git_root() {
  local root_dir
  root_dir=$(_ymt_git_root_dir) || return 1
  cd "$root_dir"
}

case ${1} in
  -h|--help)
    _ymt_git_root_usage
  ;;

  show)
    _ymt_git_root_dir
  ;;

  *)
    _ymt_git_root
  ;;
esac
