#!/bin/zsh

set -e

local json=$(curl --silent https://api.github.com/repos/fillin-inc/templates/contents/rails | jq '.[]')

local template=$(echo ${json} | jq '.name' | grep '.rb' | sed -e 's/"//g' | sed -e 's/\.rb$//' | peco)
if [ -z $template ]; then
  echo "failed to retrieve templates."
  return 1
fi

local selected=$(echo ${json} | jq ". | select (.name == \"${template}.rb\") | .download_url" | sed -e 's/"//g')
if [ -z $selected ]; then
  echo "failed to get the download_url for the selected template."
  return 1
fi

# create commit
if [ ! -d .git ]; then
  git init
  git commit --allow-empty -m "initial commit"
fi

# download defaulg Gemfile
if [ ! -f "Gemfile" ]; then
  curl -O --silent https://raw.githubusercontent.com/fillin-inc/templates/master/rails/example/Gemfile
fi

bundle config set without 'production'
bundle i

if [[ $template == *"api"* ]]; then
  bundle exec rails new . -v --force -m $selected -d mysql --skip-action-text --skip-action-mailbox --skip-action-cable --skip-turbolinks --skip-test --api
else
  bundle exec rails new . -v --force -m $selected -d mysql --skip-action-text --skip-action-mailbox --skip-action-cable --skip-turbolinks --skip-test --webpacker
fi
