#!/bin/zsh

set -e

local json=$(curl --silent https://api.github.com/repos/fillin-inc/templates/contents/docker-compose | jq '.[]')

local template=$(echo ${json} | jq '.name' | grep '.yml' | sed -e 's/"//g' | sed -e 's/\.yml$//' | peco)
if [ -z $template ]; then
  echo "failed to retrieve templates."
  return 1
fi

echo "TEMPLATE: $template"

local selected=$(echo ${json} | jq ". | select (.name == \"${template}.yml\") | .download_url" | sed -e 's/"//g')
if [ -z $selected ]; then
  echo "failed to get the download_url for the selected template."
  return 1
fi

echo "download_url: $selected"

curl -o docker-compose.yml --silent $selected
