#!bin/zsh

_ymt_tmx_usage() {
  cat <<EOF
tmx is a command to support tmux operations.

Usage:
    tmx                start base session
    tmx [name]         start or switch [name] session
    tmx list           list sessions
    tmx attach         attach/switch session
    tmx switch         attach/switch session
    tmx detach         detach session
    tmx kill [name]    kill [name] session

Options:
    --help, -h         print help

Dependencies:
    tmux
    peco
EOF
}

_ymt_tmx_switch() {
  local session=${1}
  if [ -z "${session}" ]; then
    # 未指定の場合 peco から選択
    session="$(tmux list-sessions | peco --prompt='session >' | cut -d : -f 1)"
  fi

  if [ -n "$session" ]; then
    if [ -n "$TMUX" ]; then
      tmux switch -t $session
    else
      tmux attach -t $session
    fi
  fi
}

_ymt_tmx_kill() {
  if [ -z "${1}" ]; then
    echo 'Specify the session to be killed.'
    return 1
  fi
  tmux kill-session -t ${1}
}

_ymt_tmx() {
  local session=${1}
  if [ -z $session ]; then
    session='base'
  fi
  local sessions=($(tmux list-sessions | sed -r 's/^(.+): .+$/\1/'))

  # 一致する session がある場合には switch
  if [[ "${sessions[@]}" =~ "${session}" ]]; then
    _ymt_tmx_switch $session
  else
    tmux new -A -s $session
  fi
}

case ${1} in
  -h|--help)
    _ymt_tmx_usage
  ;;

  list|l)
    tmux list-sessions
  ;;

  attach|a|switch|s)
    _ymt_tmx_switch ${2}
  ;;

  detach|d)
    tmux detach
  ;;

  kill|k)
    _ymt_tmx_kill ${2}
  ;;

  *)
    _ymt_tmx ${1}
  ;;
esac
