#!bin/zsh

_ymt_tmx_usage() {
  cat <<EOF
tmx is a command to support tmux operations.

Usage:
    tmx                start base session
    tmx [name]         start [name] session
    tmx list           list sessions
    tmx attach         attach/switch session
    tmx switch         attach/switch session
    tmx detach         detach session
    tmx kill [name]    kill [name] session

Options:
    --help, -h         print help

Dependencies:
    tmux
    peco
EOF
}

_ymt_tmx_switch() {
  local session="$(tmux list-sessions | peco --prompt='session >' | cut -d : -f 1)"
  if [ -n "$session" ]; then
    if [ -n "$TMUX" ]; then
      tmux switch -t $session
    else
      tmux attach -t $session
    fi
  fi
}

_ymt_tmx() {
  local session=${1}
  if [ -z $session ]; then
    session='base'
  fi
  tmux new -A -s $session
}

case ${1} in
  -h|--help)
    _ymt_tmx_usage
  ;;

  list|l)
    tmux list-sessions
  ;;

  attach|a|switch|s)
    _ymt_tmx_switch
  ;;

  detach|d)
    tmux detach
  ;;

  kill|k)
    if [ -z "${2}" ]; then
      echo 'Specify the session to be killed.'
      return 1
    fi
    tmux kill-session -t ${2}
  ;;

  *)
    _ymt_tmx ${1}
  ;;
esac
