#!/bin/zsh

local current_dir=$(pwd)
read MARKDOWN_FILENAME\?"Enter a file name: "
read MARKDOWN_DIR\?"Enter the directory(${current_dir}): "

local dir=$(eval echo ${MARKDOWN_DIR:-${current_dir}})
local file_path="${dir}/$(date '+%Y%m%d')_$(echo $MARKDOWN_FILENAME | sed -e 's/\s\+/_/g').md"
unset MARKDOWN_FILENAME MARKDOWN_DIR

if [ ! -d $dir ]; then
  echo "There is no directory: ${dir}. Do you want to create it?(y/n)"
  if read -q; then
    echo "\nCreating a directory: ${dir}"
    mkdir -p $dir
  else
    echo "\nStopped creating the file."
    return
  fi
fi

if [ ! -f $file_path ];then
  echo "Create a markdown file: ${file_path}"
  echo "# ${input}" > $file_path
fi
vi $file_path
