#!/bin/zsh

function _ymt_vip_usage() {
  cat <<EOF
vip is a command to select a file shown in git status and edit it with vim.

Usage:
    vip            select file and edit
    vip absolute   select file and edit
    vip relative   select file by relative path and edit

Options:
    --help, -h     print help

Dependencies:
    peco
    git
    vim
EOF
}

function _ymt_vip_relative_path() {
  local root_dir=$(git rev-parse --show-toplevel 2>/dev/null)
  if [ -z $root_dir ]; then
    echo "not under git control."
    return 1
  fi

  local selected=$(git status -s | awk '{ print $2 }' | peco --query "$LBUFFER")
  vi $selected
}

function _ymt_vip_absolute_path() {
  local root_dir=$(git rev-parse --show-toplevel 2>/dev/null)
  if [ -z $root_dir ]; then
    echo "not under git control."
    return 1
  fi

  local selected=$(cd $root_dir;git status -s | awk '{ print $2 }' | peco --query "$LBUFFER")
  vi $selected
}

case ${1} in
  -h|--help)
    _ymt_vip_usage
  ;;

  relative)
    _ymt_vip_relative_path
  ;;

  absolute|*)
    _ymt_vip_absolute_path
  ;;
esac
